"""Pin the Phase 4.9 ``upstream_silent`` contract.

When the gateway's configured ``upstream_timeout_secs`` fires
before the upstream LLM responds, the chat handler must:

* Return HTTP 503 with body
  ``{"error": {"type": "upstream_silent", "timeout_secs": N,
  "alias": ..., "request_id": ..., "message": ...}}``.
* Log one ``chat.completion`` row with ``status="upstream_silent"``
  and the configured ``timeout_secs``.
* Not wait forever — the response must arrive within the
  configured timeout plus a small margin.

The orphan ``dispatch_task`` continues running under
``asyncio.shield`` after the response is returned. v1 doesn't
read its eventual outcome (no reaper); we just pin that the
task being orphaned doesn't crash the gateway.
"""

from __future__ import annotations

import asyncio
from collections.abc import Iterator
from pathlib import Path
from typing import Any

import pytest
from fastapi.testclient import TestClient

from gateway.app import create_app

from ._fixtures import PERSONAL_TOKEN, build_test_config


@pytest.fixture
def captured_log_events(monkeypatch: pytest.MonkeyPatch) -> Iterator[list[dict[str, Any]]]:
    """Spy on ``gateway.chat.log_request`` (same pattern as
    ``test_chat_error_logging.py``) so we can pin the structured
    fields of the ``upstream_silent`` event without configuring
    the global logging chain."""
    events: list[dict[str, Any]] = []

    def fake_log_request(_logger: Any, **fields: Any) -> None:
        events.append(dict(fields))

    monkeypatch.setattr("gateway.chat.log_request", fake_log_request)
    yield events


def _build_client(tmp_path: Path, *, upstream_timeout_secs: float = 0.2) -> TestClient:
    """A test app whose upstream timeout is tight enough that
    a stubbed always-blocking LiteLLM trips it within the test's
    own deadline."""
    cfg = build_test_config(tmp_path)
    cfg.upstream_timeout_secs = upstream_timeout_secs
    app = create_app(cfg)
    return TestClient(app)


def _auth() -> dict[str, str]:
    return {"Authorization": f"Bearer {PERSONAL_TOKEN}"}


# ----------------------------------------------------- happy timeout


def test_upstream_silent_returns_503_with_typed_error_body(
    tmp_path: Path,
    captured_log_events: list[dict[str, Any]],
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """When LiteLLM blocks past ``upstream_timeout_secs``, the
    gateway returns 503 ``upstream_silent`` within
    ``timeout + ~1s`` (not LiteLLM's own ~600s default)."""

    async def fake(**_: Any) -> Any:
        # Block forever — caller's wait_for must trip first.
        await asyncio.sleep(60.0)
        raise AssertionError("unreachable; gateway must time out first")

    monkeypatch.setattr("gateway.router.litellm.acompletion", fake)

    client = _build_client(tmp_path, upstream_timeout_secs=0.2)
    r = client.post(
        "/v1/chat/completions",
        json={"model": "fitt-smart", "messages": [{"role": "user", "content": "hi"}]},
        headers=_auth(),
    )
    assert r.status_code == 503
    body = r.json()
    err = body["error"]
    assert err["type"] == "upstream_silent"
    assert err["timeout_secs"] == 0.2
    assert err["alias"] == "fitt-smart"
    assert "request_id" in err  # generated by the middleware
    assert "fitt-smart" in err["message"]
    # The user-facing message is what the bot will surface; pin it
    # to be the operator-readable string the spec promised.
    assert "went silent" in err["message"]


def test_upstream_silent_emits_chat_completion_with_status(
    tmp_path: Path,
    captured_log_events: list[dict[str, Any]],
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """The structured log row carries
    ``status="upstream_silent"`` plus ``timeout_secs`` so an
    operator can grep for the new failure mode without ambiguity
    against the existing ``upstream_server_error`` /
    ``no_backend_available`` rows."""

    async def fake(**_: Any) -> Any:
        await asyncio.sleep(60.0)
        raise AssertionError("unreachable")

    monkeypatch.setattr("gateway.router.litellm.acompletion", fake)

    client = _build_client(tmp_path, upstream_timeout_secs=0.1)
    client.post(
        "/v1/chat/completions",
        json={"model": "fitt-smart", "messages": [{"role": "user", "content": "hi"}]},
        headers=_auth(),
    )

    rows = [e for e in captured_log_events if e.get("status") == "upstream_silent"]
    assert len(rows) == 1, captured_log_events
    e = rows[0]
    assert e["timeout_secs"] == 0.1
    assert e["alias"] == "fitt-smart"


# ----------------------------------------------------- happy path still works


def test_fast_upstream_does_not_trigger_silent_path(
    tmp_path: Path,
    captured_log_events: list[dict[str, Any]],
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """A fast upstream completes normally — no
    ``upstream_silent`` event, no 503. Pin that the
    shielded-wait_for wrapper doesn't break the happy path."""
    from ._llm_stubs import stub_reply

    async def fake(**_: Any) -> Any:
        # Fast: well under the timeout.
        await asyncio.sleep(0.01)
        return stub_reply("hi back")

    monkeypatch.setattr("gateway.router.litellm.acompletion", fake)

    client = _build_client(tmp_path, upstream_timeout_secs=2.0)
    r = client.post(
        "/v1/chat/completions",
        json={"model": "fitt-default", "messages": [{"role": "user", "content": "hi"}]},
        headers=_auth(),
    )
    assert r.status_code == 200
    silents = [e for e in captured_log_events if e.get("status") == "upstream_silent"]
    assert len(silents) == 0


# ----------------------------------------------------- LiteLLM Timeout class


def test_litellm_timeout_classified_as_upstream_silent(
    tmp_path: Path,
    captured_log_events: list[dict[str, Any]],
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """When LiteLLM itself raises ``litellm.Timeout`` (its own
    HTTP-level timeout fired, not asyncio's wait_for), the
    classifier maps it to ``upstream_silent`` so the bot still
    shows the actionable message instead of a generic
    ``upstream_server_error``."""
    import litellm

    async def fake(**_: Any) -> Any:
        # Construct a Timeout the way litellm raises it. The class
        # carries status_code=408 by litellm convention.
        raise litellm.Timeout(
            message="Timeout Error: backend went silent",
            model="deepseek-v4-flash",
            llm_provider="openai",
        )

    monkeypatch.setattr("gateway.router.litellm.acompletion", fake)

    client = _build_client(tmp_path, upstream_timeout_secs=300.0)
    r = client.post(
        "/v1/chat/completions",
        json={"model": "fitt-smart", "messages": [{"role": "user", "content": "hi"}]},
        headers=_auth(),
    )
    assert r.status_code == 503
    body = r.json()
    assert body["error"]["type"] == "upstream_silent"
    rows = [e for e in captured_log_events if e.get("status") == "upstream_silent"]
    assert len(rows) == 1
